server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /${spring.application.name}
spring:
  datasource:
    pg:
      url: jdbc:postgresql://localhost:5432/gis
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      sql-script-encoding: utf-8
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-timeout: 30000
        idle-timeout: 60000
        max-lifetime: 1800000
        maximum-pool-size: 60
        minimum-idle: 0
    sqlite:
      url: jdbc:sqlite:empt.mbtiles
      username: postgres
      password: postgres
      driver-class-name: org.sqlite.JDBC
      sql-script-encoding: utf-8
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-timeout: 30000
        idle-timeout: 60000
        max-lifetime: 1800000
        maximum-pool-size: 60
        minimum-idle: 0
  application:
    name: jts2geojson
beetlsql:
  pg:
    sqlPath: /sql
    nameConversion: org.beetl.sql.core.UnderlinedNameConversion
    daoSuffix: Dao
    basePackage: org.fengsoft.jts2geojson.dao
    dbStyle: org.beetl.sql.core.db.PostgresStyle
  sqlite:
    sqlPath: /sql
    nameConversion: org.beetl.sql.core.UnderlinedNameConversion
    daoSuffix: Dao
    basePackage: org.fengsoft.jts2geojson.dao
    dbStyle: org.beetl.sql.core.db.SQLiteStyle
  multiple:
    datasource: pg,sqlite
beetl-beetlsql: dev=false
beetl:
  suffix: html
  templatesPath: templates

# 存放缓存文件的地址
cache:
  vector-tile-path: E:\Data\vectorTile
  image-tile-path: E:\Data\tiles
thread:
  size: 4






