/* (c) 2014 Open Source Geospatial Foundation - all rights reserved
 * (c) 2001 - 2013 OpenPlans
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
package org.geoserver.wms;

import java.io.IOException;
import java.util.List;
import java.util.Set;
import org.geoserver.platform.ServiceException;
import org.geotools.map.Layer;
import org.opengis.referencing.crs.CoordinateReferenceSystem;

/**
 *
 * @author Gabriel Roldan
 * @author Simone Giannecchini, GeoSolutions
 * @version $Id$
 */
public interface GetMapOutputFormat {
    /**
     * Asks this map producer to create a map image for the passed {@linkPlain WMSMapContext}, which
     * contains enough information for doing such a process.
     *
     * @param mapContent
     * @throws ServiceException something goes wrong
     */
    public byte[] produceMap(WMSMapContent mapContent, List<Layer> layers, CoordinateReferenceSystem coordinateReferenceSystem) throws ServiceException, IOException;

    /**
     * Returns the list of content type aliases for this output format, that are the ones to be used
     * as Format elements in the GetCapabilities document.
     *
     * <p>Aliases are used to easy the task of writing a GetMap request, (for example, to type
     * &outputformat=svg instead of the full &outputformat=image/svg+xml)
     *
     * @return the aliases a map of the content type this map producer creates content type can be
     *     asked by through a GetMap request.
     */
    public Set<String> getOutputFormatNames();

    /** Returns the mime type generated by the format */
    public String getMimeType();

    /**
     * Returns the capabilities for the specified format
     *
     * @param format
     */
    public MapProducerCapabilities getCapabilities(String format);
}
